<?php

return [
    'show_warnings'   => false,
    'orientation'     => 'landscape',
    'defines'         => [
        'DOMPDF_ENABLE_AUTOLOAD'    => false,
        'DOMPDF_ENABLE_REMOTE'      => true,
        'DOMPDF_ENABLE_HTML5PARSER' => true,
        'DOMPDF_ENABLE_FONTSUBSETTING' => true,
        'DOMPDF_UNICODE_ENABLED'    => true,
        'DOMPDF_ENABLE_JAVASCRIPT'  => false,
        'DOMPDF_DPI'                => 96,
        'DOMPDF_DEFAULT_PAPER_SIZE' => 'a4',
        'DOMPDF_DEFAULT_FONT'       => 'DejaVu Sans',
        'DOMPDF_TEMP_DIR'           => sys_get_temp_dir(),
        'DOMPDF_CHROOT'             => base_path(),
        'DOMPDF_LOG_OUTPUT_FILE'    => null,
        'DOMPDF_ENABLE_PHP'         => false,
        'DOMPDF_ENABLE_REMOTE'      => true,
    ],
    'options'         => [
        'font_dir'                  => storage_path('fonts/'),
        'font_cache'                => storage_path('fonts/'),
        'temp_dir'                  => sys_get_temp_dir(),
        'chroot'                    => realpath(base_path()),
        'allowed_protocols'         => ['file://', 'http://', 'https://'],
        'log_output_file'           => null,
        'is_php_enabled'            => false,
        'is_remote_enabled'         => true,
        'is_javascript_enabled'     => false,
        'is_html5_parser_enabled'   => true,
        'is_font_subsetting_enabled'=> true,
        'default_media_type'        => 'screen',
        'default_paper_size'        => 'a4',
        'default_paper_orientation' => 'landscape',
        'default_font'              => 'DejaVu Sans',
        'dpi'                       => 96,
        'enable_php'                => false,
        'enable_javascript'         => false,
        'enable_remote'             => true,
        'font_height_ratio'         => 1.1,
        'enable_html5_parser'       => true,
    ],
];
